library(readr)
tabela_1 <- read_csv2('podatki/T1_preb_zivorojeni_umrli_nar.prirast.csv', col_names=TRUE, skip=2, locale=locale(encoding="UTF-8"))
tabela_2 <- read_csv2('podatki/T2_spol-umrli_rojeni.csv', col_names=TRUE, skip=2, locale=locale(encoding="UTF-8"))
tabela_3 <- read_csv2('podatki/T3_selitveni-tujina_regije.csv', col_names=TRUE, skip=2, locale=locale(encoding="UTF-8"))
tabela_4 <- read_csv2('podatki/T4_regije_preb_star.skupine.csv', col_names=TRUE, skip=2, locale=locale(encoding="UTF-8"))
